### ISSUE TITLE
User story 1: List of locations 

### ISSUE THREAD

**Issue by aaaleeenaaa** [aaaleeenaaa/capstone-project#2]
## Value proposition

As a user,
I want to see a list of all locations where I have bee colonies
in order to have a good overview of them.  

## Description

![List of all locations](https://user-images.githubusercontent.com/126454016/234288550-88ee20cb-b88a-4a66-93a5-ccad236d8571.png)

## Acceptance criteria

- [ ] Header stays visible while scrolling
- [ ] For each location, one card is shown 
- [ ] Each card shows the name of the location
- [ ] Each card has the same size

## Tasks

- [ ] Create a branch
- [ ] Add a list component to the app
- [ ] Add a card component
- [ ] Add styling

**Comment by NikRoe** [comment]
Looks good 💪
