### ISSUE TITLE
User story 2: Add locations with bee colonies to the list

### ISSUE THREAD

**Issue by aaaleeenaaa** [aaaleeenaaa/capstone-project#3]
## Value proposition

As a user, 
I want to add locations with bee colonies to the list
in order to have a good, up to date overview of all of them.

## Description

![Add button leading to form where new locations can be entered, these then appear in list](https://user-images.githubusercontent.com/126454016/234293350-84963f77-7c51-4d7f-9dad-b320c4a59d62.png)

## Acceptance criteria

- [ ] Header stays visible all the time
- [ ] Click on add button leads to a form where a new location can be entered
- [ ] Submitting the form leads to the new location being shown in the list 
- [ ] Form cannot be empty when being submitted 
- [ ] Add button always visible on list page but not on page with form 

## Tasks

- [ ] Create a branch
- [ ] Add an add button to page with list 
- [ ] Add a form with label, text field and submit button
- [ ] Click on add button leads to the form
- [ ] Submitting the form leads to the new location being shown in the list
- [ ] Add styling
