### ISSUE TITLE
User story 3: List of bee colonies for each location 

### ISSUE THREAD

**Issue by aaaleeenaaa** [aaaleeenaaa/capstone-project#4]
## Value proposition

As a user, 
I want to have a list of the bee colonies I have at each location
in order to have an overview of how many bee colonies I have at which location.

## Description

![Click on location leads to its detail page showing the bee colonies there](https://user-images.githubusercontent.com/126454016/234296958-cc2b567f-98b5-4713-af24-165dc41745fd.png)

## Acceptance criteria

- [ ] Header stays visible all the time
- [ ] Click on location leads to list of colonies there
- [ ] List heading shows name of location 
- [ ] For each bee colony, one card is shown 
- [ ] Each card shows the name of the bee colony
- [ ] Each card has the same size

## Tasks

- [ ] Create a branch
- [ ] Create a detail page for each location
- [ ] Click on location leads to detail page
- [ ] Add list component to detail page
- [ ] Add heading and cards to list
- [ ] Add styling
