### ISSUE TITLE
User story 4: Add list of bee colonies to detail page of each location

### ISSUE THREAD

**Issue by aaaleeenaaa** [aaaleeenaaa/capstone-project#5]
## Value proposition

As a user, 
I want to add bee colonies to the detail page of each location
in order to have an up to date overview of how many colonies I have at which location.

## Description

![Click on location leads to detail page, there an add button leads to a form where new colonies can be added, these then appear on detail page](https://user-images.githubusercontent.com/126454016/234302018-123fb34c-58e9-4f52-82c7-03bfecc803d4.png)

## Acceptance criteria

- [ ] Header stays visible all the time
- [ ] Click on add button leads to form where a new bee colony can be entered 
- [ ] Form cannot be empty when being submitted 
- [ ] Submitting the form leads to the new bee colony being shown in the list on the location's detail page 
- [ ] Add button always visible on location's detail page but not on page with form

## Tasks

- [ ] Create a branch
- [ ] Add an add button to location's detail page
- [ ] Add a form with label, text field and submit button
- [ ] Click on add button leads to the form
- [ ] Submitting the form leads to the new bee colony being shown in the list
- [ ] Add styling
