### ISSUE TITLE
User story 5: Add detail page for each bee colony

### ISSUE THREAD

**Issue by aaaleeenaaa** [aaaleeenaaa/capstone-project#6]
## Value proposition

As a user, 
I want to have a detail page with a checklist for each bee colony 
in order to easily keep hold of information about them. 

## Description

![Click on colony leads to detail page, this contains a checklist with heading and question cards](https://user-images.githubusercontent.com/126454016/234310423-94cde6d9-ac19-4f04-923a-f86a146eee3e.png)

## Acceptance criteria

- [ ] Header stays visible all the time
- [ ] Click on colony leads to its detail page
- [ ] Detail page contains list with heading and question cards
- [ ] Heading contains name of location and name of colony
- [ ] Question cards contain a question and answer options depending on type of question (checkboxes, textfield with submit button etc.) 

## Tasks

- [ ] Create a branch
- [ ] Create a detail page for each colony
- [ ] Create a card component with questions and answer options
- [ ] Add list with heading and cards to the colony's detail page
- [ ] Add styling
